del /S *.~*
del /S *.bdsgroup.local
del /S *.bdsproj.local
del /S *.bpi
del /S *.bpl
del /S *.cfg
del /S *.dcp
del /S *.dcu
del /S *.dproj.local
del /S *.drc
del /S *.dsk
del /S *.exe
del /S *.groupproj.local
del /S *.hpp
del /S *.identcache
del /S *.lib
del /S *.map
del /S *.obj
del /S *.tds
del /S *.tgs
del /S *.tgw
rmdir __history